web:
  image: nginx
  volumes:
    - nginx-owncloud.conf:/etc/nginx/conf.d/nginx-owncloud.conf:ro
    - nginx.conf:/etc/nginx/nginx.conf:ro
    - cert:/cert
  links:
    - app
  volumes_from:
    - app
  ports:
    - 443
app:
  image: indiehosters/owncloud
  links:
    - db:mysql
    - memcached
  volumes:
    - data/apps:/var/www/html/apps
    - data/config:/var/www/html/config
    - data/data:/var/www/html/data
  environment:
    ROOT_URL: 'localhost'
db:
  image: mysql
  volumes:
    - data/mysql/runtime:/var/lib/mysql
    - data/mysql/dump:/dump
  environment:
    MYSQL_ROOT_PASSWORD
memcached:
  image: memcached

